week4: 4차 필수과제 진행(xml)
NOW-SOPT-ANDROID/minjae-son pull request #10
Opened 2024-05-03 14:12 UTC by SYAAINN

## Related issue 🛠
- closed #9 

## Work Description ✏️
- 회원가입 서버 통신
- 로그인 서버 통신
- 마이페이지에 로그인 정보 노출

## Screenshot 📸

https://github.com/NOW-SOPT-ANDROID/minjae-son/assets/137160756/d1b83420-c7f5-49cf-9013-3b042f77b58d

## Uncompleted Tasks 😅
- [ ] HomeFragment에 OpenAPI 연결하기
- [ ] 비밀번호 변경 기능

## To Reviewers 📢
과제 명세 완료할 수 있도록 계속 디벨롭 하겠습니다 ,, ㅠ

2024-05-05 01:22 UTC, arinming reviewed
서버 통신 어려우셨을 텐데 열심히하신게 느껴집네다...!!!!!!!!!

2024-05-05 01:22 UTC, arinming commented on app/src/main/java/com/sopt/now/activity/SignInActivity.kt
> +    private val viewModel by viewModels<SignInViewModel>()
by viewModels로 초기화될 수 있는 건 몰랐는데 알아갑니당 ㅎㅎ

2024-05-05 01:22 UTC, arinming commented on app/src/main/java/com/sopt/now/activity/SignUpActivity.kt
함수화가 너무 깔끔해여 !

2024-05-05 01:22 UTC, arinming commented on app/src/main/java/com/sopt/now/data/ResponseSignInDto.kt
> +    val status: Int,
code, status 통일이 안되어 있는데 이유가 있으실까여?

2024-05-05 01:22 UTC, arinming commented on app/src/main/java/com/sopt/now/myPageFragment/MyPageFragment.kt
> +                }
여기도 뷰모델로 리팩토링하시면 깔끔할 듯 합니당 !

2024-05-05 01:22 UTC, arinming commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +    }
네비게이션을 뷰모델로 구현하셨네여!

2024-05-05 01:22 UTC, arinming commented on app/src/main/res/values/strings.xml
snake 네이밍 방식으로 하면 모든 글자가 소문자여야 하는 걸로 알고이써요!

2024-05-05 08:35 UTC, yeonjeen reviewed
이야... 너무 잘해서 할 말을 잃었... 넘 수고많으셨어용!!!!

2024-05-05 08:35 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/activity/SignUpActivity.kt
성장속도 무엇...

2024-05-05 08:35 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/homeFragment/HomeViewModel.kt
>      )
여기 mock 데이터는 없어도 되지 않을까용...?

2024-05-05 14:57 UTC, junseo511 requested changes
진짜 정말정말 항상 고생 많으십니다 ㅠㅠ 늘 파이팅!!! 포기하지 말고 같이 달려봐요

2024-05-05 14:57 UTC, junseo511 commented on app/build.gradle
> +    implementation("com.squareup.okhttp3:logging-interceptor")
정리할때 일관성을 지켜주시면 좋을거같아용

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/MainActivity.kt
> +        Log.e("MainActivity", "memberId: ${memberId}")
불필요한 로그는 지워주세요~~!!!!

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/MainActivity.kt
>          }
함수분리를 해주심이 어떨까요?

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/SignInActivity.kt
> +    private fun initObserver() {
함수 이름을 명확하게 해주시면 좋을거같슴당

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/SignUpActivity.kt
> +    private fun initViews() {
음~~ 이친구도 함수명이 애매해요!!!!

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/activity/SignUpActivity.kt
> +        val phoneNumber = binding.etSignUpPhoneNumber.text.toString()
with(binding) 어떠세요?

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/data/ResponseSignInDto.kt
> +    val status: Int,
ㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/homeFragment/HomeViewModel.kt
>      val mockFriendProfileList = listOf(
이친구는 이제 날려주셔도 좋지 않을까요~~!!

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/myPageFragment/MyPageFragment.kt
> +                }
이제 슬슬 MVVM 패턴을 익히실 때입니다...!

2024-05-05 14:57 UTC, junseo511 commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +    }
더 좋은 방법이 있을 것 같습니다!

2024-05-06 16:47 UTC, briandr97 requested changes
안녕하세요 민재님, 민재님의 리뷰어를 맡게된 권용민이라고 합니다!

필수 과제에 xml과 compose가 있는데요 xml은 제가, compose는 준원님께서 리뷰해주실 예정입니다.
코드에 정답이 없으며, 저희 또한 많이 부족한 사람이므로 공통 로직에서 저와 준원님의 의견이 상충될 수 있습니다. 혹시 그런 상황이 발생한다면, 민재님께서 생각하시는대로 진행하고 말씀해주시면 됩니다!

또 제가 리뷰해드린 내용이라고 해서 정답은 아닙니다. 사람마다 생각이 다를 수 있으며, 제가 틀렸을 수도 있습니다. 납득이 되지 않으면 언제든 질문주시고, 민재님의 생각을 말씀해주세요!

과제하느라 고생하셨습니다! 잘부탁드립니다!

모든 리뷰에 1~5에 해당하는 번호를 남겼습니다. 해당 번호들은 중요도를 나타냅니다.
1,2번은 changes requested,
3번은 comment,
4,5번은 추가정보 정도로 생각해주시면 좋을 것 같습니다.

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/activity/SignInActivity.kt
> +        viewModel.liveData.observe(this) {
[1]
뷰모델에 존재하는 상태의 변수명이 `liveData`인 이유가 있을까요?
변수명은 타입을 나타내기보다 어떤 역할을 하는지 알 수 있게 해주는 것이 좋습니다.

만약 다른 사람이 혹은 몇개월 후의 민재님이 이 코드를 보았을때 어떤 정보를 관찰하고 있는지 알 수 있을까요?

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/activity/SignInActivity.kt
>              }
[1]
변수명의 첫 글자는 소문자로 하는 것이 코틀린 공식 컨벤션입니다.
대문자를 사용하게 되면 위와 같이 `SignInState.message`, `SignInState.memberId`라고 썼을 때 다른 사람들은 `SignInState`가 인스턴스라고 인지하기 어렵습니다. object 혹은 companion object로 인지할 확률히 매우 높습니다.

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/data/ResponseUserInfoDto.kt
> +        val defalutUser = UserInfo()
[3]
이 친구의 용도는 뭘까요?

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/myPageFragment/MyPageFragment.kt
> +    }
[3]
![image](https://github.com/Graduztion-Project/graduation-android/assets/78788847/70e8f269-9f4e-411f-87bb-882e663dd5f4)
코틀린 컨벤션에 의하면 동반객체가 제일 마지막에 옵니다!

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/myPageFragment/MyPageFragment.kt
> +                        Toast.makeText(requireContext(), "회원 정보를 가져오는데 실패했습니다.", Toast.LENGTH_SHORT)
[2]
문자를 하드코딩 하는 것과 `strings.xml`에 넣는 것의 기준이 뭘까요?

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignInViewModel.kt
> +    val liveData = MutableLiveData<SignInState>()
[1]
위에서 말했듯이 이런 변수명은 좋지 않습니다.

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignInViewModel.kt
> +    val liveData = MutableLiveData<SignInState>()
[2]
현재 요구사항에서 `liveData` 변수는 뷰모델 내에서만 변경되며 밖에서는 변경할 필요가 없습니다.
하지만 현재 구조는 밖에서 얼마든지 `liveData.value = signInState`로 바꿀 수 있는 상태입니다.
캡슐화와 정보 은닉의 관점에서 어떻게 바꿔볼 수 있을까요?

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +    val liveData = MutableLiveData<SignUpState>()
[1]
위에서 했던 리뷰와 같습니다.

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +        get() = _navigateToSignIn
[1]
`navigateToSignIn`만 봐서는 로그인으로 갈 수 있는 지를 나타내는 변수인지 알 수 없습니다.
그래서 보통 `Boolean`형태의 변수에는 `is` 혹은 `can`과 같은 접두사가 붙습니다.

`canNavigateToSignIn`과 같은 형태가 된다면 더 의미가 와닿을 것 같습니다.

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +        get() = _navigateToSignIn
[5]
여기서는 `backing property`로 잘 만들어주셨네요!
위에서 리뷰드린 내용이었었는데, 알고 계셨던 거라면 수정해주시고, 모르고 사용하셨더라면 `backing property`에 대해 알아보시면 좋을 것 같습니다.

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +                    Log.d("SignUp", "data: $data, userId: $userId")
[5]
개발 중에 작성하신 로그는 지워주시는게 좋습니다!

2024-05-06 16:47 UTC, briandr97 commented on app/src/main/java/com/sopt/now/viewModel/SignUpViewModel.kt
> +                        message = "회원가입 실패 $error"
[2]
위에서 말씀드렸던 내용이지만, 민재님께서 문자를 하드 코딩하는 것과 `strings.xml`에 넣는 것을 구분한 기준이 무엇일까요?

2024-05-06 17:24 UTC, murjune commented on app/src/main/java/com/sopt/now/myPageFragment/MyPageFragment.kt
> +                }
> 이제 슬슬 MVVM 패턴을 익히실 때입니다...!

왜 이런 생각을 하셨는지 궁금합니다!

2024-05-24 12:54 UTC, junseo511 approved these changes

2024-05-24 14:47 UTC, merged