week4: 4차 필수과제 진행(Compose)
NOW-SOPT-ANDROID/minjae-son pull request #11
Opened 2024-05-03 14:38 UTC by SYAAINN

## Related issue 🛠
- closed #9 

## Work Description ✏️
- 서버 통신 기초 파일 작성
- 파일 리패키징

## Screenshot 📸

## Uncompleted Tasks 😅
- [ ] 회원가입 서버 통신
- [ ] 로그인 서버 통신
- [ ] 마이페이지 로그인 정보 노출
- [ ] 홈 화면 OpenAPI 구현

## To Reviewers 📢
늦었지만,, 빠르게 달려보겠습니다..ㅠ

2024-05-05 01:24 UTC, arinming reviewed
리팩토링 아자잣~~~!

2024-05-05 14:58 UTC, junseo511 requested changes
선생님,,,! 파이팅이예요

2024-05-05 14:58 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/ApiFactory.kt
> +}
저희가 사용해야 하는 api는 두개랍니다 🤭

2024-05-06 17:18 UTC, murjune requested changes
안녕하세요. 민재님 리뷰어로 함께하게 된 명예OB 이준원입니다. 

아직 과제 완수를 하지 않으신 것 같습니다.(서버 연동을 하지 않은 것 같네요..? 👀 )  

과제를 완수하고 리뷰 요청 부탁드립니다 🙏

2024-05-06 17:18 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ApiFactory.kt
> +}
```suggestion
object ApiFactory {
    private const val BASE_URL: String = BuildConfig.AUTH_BASE_URL

    val retrofit: Retrofit by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
            .build()
    }

    inline fun <reified T> create(): T = retrofit.create()
}
```

class Type을 매개변수로 넘겨주지 않아도 됩니다!

2024-05-06 17:18 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/ApiFactory.kt
> +}
현재 해당 service 객체를 사용하고 있지 않습니다 👀

2024-05-06 17:18 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/main/home/HomeViewModel.kt
> +package com.sopt.now.compose.main.home
main 이라는 package 명을 보면 동료개발자가 해당 패키지에 어떤 class들이 들어있는지 알 수 있을까요??

2024-05-06 17:18 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/service/AuthService.kt
> +    @POST("member/join") //http 메소드
👍

2024-05-06 17:18 UTC, murjune commented on app/src/main/java/com/sopt/now/compose/service/AuthService.kt
> +    ): Call<ResponseSignUpDto> //비동기->callback
다만, 불필요한 주석은 삭제해주세요!

2024-05-24 12:55 UTC, junseo511 approved these changes

2024-05-24 14:47 UTC, merged