Feat/week compose1
NOW-SOPT-ANDROID/minjae-son pull request #4
Opened 2024-04-05 14:48 UTC by SYAAINN

## Related issue 🛠
- closed #1 

## Work Description ✏️
- 로그인 페이지 구현
- 회원가입 페이지 구현
- 메인 페이지 구현
- 페이지 간 이동 기능 구현

## Screenshot 📸

https://github.com/NOW-SOPT-ANDROID/minjae-son/assets/137160756/b98debfd-996c-403d-a8da-c19082a85227

## Uncompleted Tasks 😅
- [ ] 회원가입 조건 검사 기능
- [ ] 회원가입 정보 바탕으로 로그인 여부 확인 기능
- [ ] 로그인 정보로 메인화면 정보 구성 기능

## To Reviewers 📢
XML 은 어찌저찌 했으나.. Compose 는 시간이 많이 부족했습니다.. ㅠ
멈추지 않고 계속 디벨롭 하겠습니다..!

2024-04-05 15:50 UTC, arinming reviewed
컴포즈 첨인데도 수고하셨어요!!!! 컴포즈는 뷰가 그대로 코드에 들어가서 반복되는 코드가 조금만 많아져도 코드 길이가 뿅 길어져서 재사용 할 수 있는 건 하는 게 가독성에 도움이 많이 된답니당 파이팅

2024-04-05 15:50 UTC, arinming commented on app/src/main/AndroidManifest.xml
> +            android:name=".SignInActivity"
SignIn, SignUp으로 맞춘거 편-안하네요..저도 그래야겠ㅇ어요

2024-04-05 15:50 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +                text = "SOPT에 온걸 환영해!",
text = stringResource(id = ) 로 구현하면 짱짱

2024-04-05 15:50 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +                textAlign = TextAlign.Center
동일한 size, weight, align이 적용되는 텍스트는 한 컴포저블로 묶으면 재사용하기 편하다는 사아실

2024-04-05 15:50 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignInActivity.kt
> +                    .fillMaxWidth()
텍스트 필드도 마찬가지로 공통되는 부분을 한 컴포저블로 묶으면 어떤 value인지만 전달해줘서 이후 대규모 작업할 때 가독성이 훨씬 좋아질 것 같아용!

2024-04-05 15:50 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignInActivity.kt
> +                leadingIcon = { Icon(Icons.Filled.Lock, contentDescription = "PW Icon") },
아이콘 설정 깨알같구 좋네용 ㅎㅎ

2024-04-05 15:50 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignInActivity.kt
> +                shape = RoundedCornerShape(8.dp)
버튼도 동일한 스타일이 반복되는 것 같아요!
대신 OutlineButton 활용하면 자동으로 코너세이프가 적용되어있어서 둥글둥글해여 이외에도 IconButton 등 여러 버튼이 많아서 찾아보면 좋을 것 같읍니다

2024-04-05 15:50 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +                singleLine = true,
요 설정 좋우네요

2024-04-07 14:53 UTC, yeonjeen reviewed
진짜 처음이라 저도 너무 막막했는데 진짜 고생하셨어요..!! 앞으로 컴포즈 열심히 해봐용

2024-04-07 14:53 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +                MainScreen()
컴포즈에서 유독 screen이라는 표현을 자주 보는 것 같아요!

2024-04-07 14:53 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/SignInActivity.kt
> +            // Title
리펙할때 주석 지워주세용

2024-04-07 14:53 UTC, yeonjeen commented on app/src/main/java/com/sopt/now/compose/SignUpActivity.kt
> +                    val intent = Intent(context, SignInActivity::class.java)
인텐트 부분도 함수로 분리해보셔도 좋을 것 같아용

2024-04-07 15:35 UTC, junseo511 requested changes
기능까지 모두 구현해서 시연영상 올려보도록 하죠~~!!

도움이 필요하시다면 언제든지 부르세요 파이팅입니다 😄

2024-04-07 15:35 UTC, junseo511 commented on app/src/main/AndroidManifest.xml
> +            android:theme="@style/Theme.NOWSOPTAndroid" />
activity를 하나만 쓰는 방법도 있다던데 같이 알아봐요~~!!

2024-04-07 15:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +                MainScreen()
activity를 쓰는 xml 대신 screen으로 선언하는 것처럼 보이네요 🧐

2024-04-07 15:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +                .padding(horizontal = 30.dp),
예쁘게 전체 modifier를 넎어주셧네요 굿굿~

2024-04-07 15:35 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/SignInActivity.kt
> +            NOWSOPTAndroidTheme {
https://developer.android.com/codelabs/jetpack-compose-theming?hl=ko

공식문서는 잘 보셨나요~~?

2024-04-14 12:18 UTC, arinming approved these changes
컴포즈 천재인가료????? 수고해씁니다

2024-04-14 12:18 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
> +                        Place = backStackEntry.arguments?.getString("Place") ?: "")
여러 액티비티 없이 NavHost로 구현 성공하셨네요!!!! 최곱니당

2024-04-14 12:18 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/Sources.kt
> +}
컴포넌트 따로 분리하니까 훨씬 깔끔하네용!

2024-04-14 12:18 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/Sources.kt
> +}
추후 뷰모델로도 구현해보고 싶은 부분이군욥!

2024-04-14 12:18 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/screen/MyPageScreen.kt
> +        MyPageText(text = Place)
하드코딩 문자열 처리까지 하시고 너무너무 깔끔하네ㅕ

2024-04-14 12:18 UTC, arinming commented on app/src/main/java/com/sopt/now/compose/screen/SignUpScreen.kt
> +            stringResource(R.string.tf_SignUp_Name_Hint),
SignUp, SignIn이 분리되어서 좋으네요

2024-04-14 13:12 UTC, junseo511 approved these changes
와~~ 정말로 집념과 노력이 느껴지는 리팩토링 👏👏

고생 많이하셨습니다!!!!

2024-04-14 13:12 UTC, junseo511 commented on app/build.gradle
> +    implementation platform('androidx.compose:compose-bom:2024.04.00')
갑자기 업데이트된 이유가 있나요?!

2024-04-14 13:12 UTC, junseo511 commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-compose:2.7.7'
이친구 주석 그대로 붙여두고 아래로 분리해주시면 읽기 좋을거같아요~~

2024-04-14 13:12 UTC, junseo511 commented on app/src/main/java/com/sopt/now/compose/MainActivity.kt
>              }
크 NavHost를 배우셨군요~~ 저도 리팩할때 넣어야겠슴당

2024-04-15 12:20 UTC, merged